# fish completion for affi
complete -c affi -f
complete -c affi -n "__fish_use_subcommand" -a receipt -d "Receipt operations"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a emit      -d "Append an operation-event"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a assemble  -d "Finalize into immutable receipt"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a verify    -d "Run 7-stage certify pipeline (ACCEPT/REJECT)"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a show      -d "Display receipt without verdict (ADR-5)"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a inspect   -d "Structural analysis (chicago-tdd)"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a model     -d "Process discovery (wasm4pm)"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a diagnose  -d "LSP-shaped diagnostics (lsp-max)"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a conformance -d "Fitness + activity_coverage + simplicity"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a replay    -d "Step-by-step event trace"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a graph     -d "Directly-follows graph (wasm4pm)"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a stats     -d "Aggregate counts + conformance"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a mutate    -d "Tamper-evidence demonstration"
complete -c affi -n "__fish_seen_subcommand_from receipt" -a bench     -d "Inline performance check"
complete -c affi -n "__fish_seen_subcommand_from receipt; and __fish_seen_subcommand_from emit"     -l type    -d "Event type"
complete -c affi -n "__fish_seen_subcommand_from receipt; and __fish_seen_subcommand_from emit"     -l object  -d "Object reference (id:type or id:type/qualifier)"
complete -c affi -n "__fish_seen_subcommand_from receipt; and __fish_seen_subcommand_from emit"     -l payload -d "Payload (string or - for stdin)"
complete -c affi -n "__fish_seen_subcommand_from receipt; and __fish_seen_subcommand_from assemble" -l out     -d "Output path for receipt JSON"
